name: trackit
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.0
  flutter_native_splash: ^2.3.10
  google_fonts: ^6.0.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^7.0.1
  cloud_firestore: ^5.1.0
  flutter_spinkit: ^5.2.1
  firebase_ui_firestore: ^1.6.2
  flutter_launcher_icons: ^0.13.0
  local_auth: ^2.1.7
  image_picker: ^1.1.2
  firebase_storage: ^12.1.2
  firebase_app_check: ^0.3.0+2
  intl: ^0.19.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/AppIcons/appstore.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/AppIcons/android/mipmap-xxhdpi/ic_launcher.png"
  remove_alpha_ios: true



  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  # Add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
     - family: Lilita_One
       fonts:
         - asset: fonts/Lilita_One/LilitaOne-Regular.ttf

     - family: Nunito
       fonts:
         - asset: fonts/Nunito/static/Nunito-Bold.ttf
         - asset: fonts/Nunito/static/Nunito-Medium.ttf
           weight: 600
